"""initial schema

Revision ID: 539c2c029f55
Revises: 
Create Date: 2026-09-09 20:46:41.403131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539c2c029f55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_levels_order'), 'levels', ['order'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('grammar_topics',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_topics_level_id'), 'grammar_topics', ['level_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('current_level', sa.String(length=30), nullable=False),
    sa.Column('learning_goal', sa.String(length=255), nullable=True),
    sa.Column('preferred_learning_style', sa.String(length=50), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_user_id'), 'learner_profiles', ['user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('units',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_level_id'), 'units', ['level_id'], unique=False)
    op.create_table('vocabulary',
    sa.Column('igbo_text', sa.String(length=120), nullable=False),
    sa.Column('english_text', sa.String(length=120), nullable=False),
    sa.Column('part_of_speech', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_igbo_text'), 'vocabulary', ['igbo_text'], unique=False)
    op.create_index(op.f('ix_vocabulary_level_id'), 'vocabulary', ['level_id'], unique=False)
    op.create_table('assessments',
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_unit_id'), 'assessments', ['unit_id'], unique=False)
    op.create_table('conversations',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_learner_id'), 'conversations', ['learner_id'], unique=False)
    op.create_table('learner_progress',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'scope_type', 'scope_id', name='uq_progress_scope')
    )
    op.create_index(op.f('ix_learner_progress_learner_id'), 'learner_progress', ['learner_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_created_at'), 'learning_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_learner_id'), 'learning_events', ['learner_id'], unique=False)
    op.create_table('lessons',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_unit_id'), 'lessons', ['unit_id'], unique=False)
    op.create_table('mastery',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('skill_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'skill_type', 'reference_id', name='uq_mastery')
    )
    op.create_index(op.f('ix_mastery_learner_id'), 'mastery', ['learner_id'], unique=False)
    op.create_table('review_items',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'item_type', 'item_id', name='uq_review_item')
    )
    op.create_index(op.f('ix_review_items_learner_id'), 'review_items', ['learner_id'], unique=False)
    op.create_index(op.f('ix_review_items_next_review_at'), 'review_items', ['next_review_at'], unique=False)
    op.create_table('vocabulary_progress',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('exposures_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'vocabulary_id', name='uq_vocab_progress')
    )
    op.create_index(op.f('ix_vocabulary_progress_learner_id'), 'vocabulary_progress', ['learner_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_progress_next_review_at'), 'vocabulary_progress', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_progress_vocabulary_id'), 'vocabulary_progress', ['vocabulary_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_table('exercises',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    op.create_table('lesson_objectives',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_objectives_lesson_id'), 'lesson_objectives', ['lesson_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'lesson_id', name='uq_lesson_progress')
    )
    op.create_index(op.f('ix_lesson_progress_learner_id'), 'lesson_progress', ['learner_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.String(length=1000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_attempts_created_at'), 'exercise_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercise_attempts_exercise_id'), 'exercise_attempts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_attempts_learner_id'), 'exercise_attempts', ['learner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_attempts_learner_id'), table_name='exercise_attempts')
    op.drop_index(op.f('ix_exercise_attempts_exercise_id'), table_name='exercise_attempts')
    op.drop_index(op.f('ix_exercise_attempts_created_at'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_learner_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_lesson_objectives_lesson_id'), table_name='lesson_objectives')
    op.drop_table('lesson_objectives')
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_vocabulary_progress_vocabulary_id'), table_name='vocabulary_progress')
    op.drop_index(op.f('ix_vocabulary_progress_next_review_at'), table_name='vocabulary_progress')
    op.drop_index(op.f('ix_vocabulary_progress_learner_id'), table_name='vocabulary_progress')
    op.drop_table('vocabulary_progress')
    op.drop_index(op.f('ix_review_items_next_review_at'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_learner_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_mastery_learner_id'), table_name='mastery')
    op.drop_table('mastery')
    op.drop_index(op.f('ix_lessons_unit_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_learning_events_learner_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_created_at'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_learner_progress_learner_id'), table_name='learner_progress')
    op.drop_table('learner_progress')
    op.drop_index(op.f('ix_conversations_learner_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_assessments_unit_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_vocabulary_level_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_igbo_text'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_units_level_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_learner_profiles_user_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_grammar_topics_level_id'), table_name='grammar_topics')
    op.drop_table('grammar_topics')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_levels_order'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
