"""phase 4: lesson content, vocabulary-lesson link, exercise explanation

Revision ID: 9fb643759572
Revises: 539c2c029f55
Create Date: 2026-09-10 08:04:13.145182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fb643759572'
down_revision: Union[str, Sequence[str], None] = '539c2c029f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('difficulty', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('lessons', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('lessons', sa.Column('grammar_topic_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lessons_grammar_topic_id'), 'lessons', ['grammar_topic_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'grammar_topics', ['grammar_topic_id'], ['id'], ondelete='SET NULL')
    op.add_column('vocabulary', sa.Column('example_sentence', sa.Text(), nullable=True))
    op.add_column('vocabulary', sa.Column('category', sa.String(length=60), nullable=True))
    op.add_column('vocabulary', sa.Column('difficulty', sa.Float(), nullable=False, server_default='0.3'))
    op.add_column('vocabulary', sa.Column('lesson_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_vocabulary_category'), 'vocabulary', ['category'], unique=False)
    op.create_index(op.f('ix_vocabulary_lesson_id'), 'vocabulary', ['lesson_id'], unique=False)
    op.create_foreign_key(None, 'vocabulary', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocabulary', type_='foreignkey')
    op.drop_index(op.f('ix_vocabulary_lesson_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_category'), table_name='vocabulary')
    op.drop_column('vocabulary', 'lesson_id')
    op.drop_column('vocabulary', 'difficulty')
    op.drop_column('vocabulary', 'category')
    op.drop_column('vocabulary', 'example_sentence')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_grammar_topic_id'), table_name='lessons')
    op.drop_column('lessons', 'grammar_topic_id')
    op.drop_column('lessons', 'examples')
    op.drop_column('lessons', 'content')
    op.drop_column('exercises', 'difficulty')
    op.drop_column('exercises', 'explanation')
    # ### end Alembic commands ###
